version: "2"
services:
  web:
    build: .
    command: "mix phoenix.server"
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/code
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
